import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { defaultRegistryPath, defaultWbsPath, profileRequiredDirs, resolveFrom } from "../core/paths.js";
import { stringifySimpleYaml } from "../core/yaml.js";
import type { Agent, Language, Profile, WbsDocument } from "../core/types.js";

function writeIfMissing(root: string, relativePath: string, content: string): boolean {
  const fullPath = resolveFrom(root, relativePath);
  if (existsSync(fullPath)) return false;
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, content, "utf8");
  return true;
}

export type InitOptions = {
  profile?: string;
  agent?: string;
  lang?: string;
};

export type AgentUpdateOptions = {
  agent?: string;
};

type AgentFile = {
  path: string;
  content: string;
};

type AgentManifest = {
  schemaVersion: "1";
  agent: Agent;
  files: Array<{ path: string; sha256: string }>;
};

const agentManifestPath = ".scwbs/agent-files.json";

function agentFiles(agent: Agent, language: Language): AgentFile[] {
  const languageLine = language === "ja" ? "Use Japanese for project-facing handoffs when practical." : "Use English for project-facing handoffs.";
  const common = `<!-- Generated by scwbs. Keep local customizations in a separate file. -->\n\n# SC-WBS project workflow\n\nFollow the repository's AGENTS.md and SC-WBS Task Contract before changing files.\n${languageLine}\n\n- Read the active Task Contract and stay within allowed paths.\n- Run required checks and collect Evidence before reporting completion.\n- Stop for Human Gate, schema, dependency, authentication, or release decisions.\n`;
  switch (agent) {
    case "codex":
      return [{ path: "AGENTS.md", content: `${common}\nUse scwbs packet --task <id> for the bounded work packet.\n` }];
    case "claude":
      return [{ path: ".claude/commands/scwbs.md", content: `${common}\nUse npm run scwbs -- packet --task <id> before implementation.\n` }];
    case "cursor":
      return [{ path: ".cursor/rules/scwbs.mdc", content: `${common}\nUse the Task Contract as the source of truth for every edit.\n` }];
    case "copilot":
      return [{ path: ".github/copilot-instructions.md", content: `${common}\nUse the repository's SC-WBS CLI commands through the npm script.\n` }];
  }
}

function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

function readAgentManifest(root: string): AgentManifest | undefined {
  const fullPath = resolveFrom(root, agentManifestPath);
  if (!existsSync(fullPath)) return undefined;
  try {
    const parsed = JSON.parse(readFileSync(fullPath, "utf8")) as AgentManifest;
    if (parsed.schemaVersion !== "1" || !Array.isArray(parsed.files)) return undefined;
    return parsed;
  } catch {
    return undefined;
  }
}

function writeAgentManifest(root: string, agent: Agent, files: AgentFile[]): void {
  const fullPath = resolveFrom(root, agentManifestPath);
  mkdirSync(dirname(fullPath), { recursive: true });
  const manifest: AgentManifest = {
    schemaVersion: "1",
    agent,
    files: files.map((file) => ({ path: file.path, sha256: sha256(file.content) }))
  };
  writeFileSync(fullPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

function syncAgentFiles(root: string, agent: Agent, language: Language, update: boolean): string[] {
  const files = agentFiles(agent, language);
  const manifest = readAgentManifest(root);
  const previous = new Map((manifest?.agent === agent ? manifest.files : []).map((file) => [file.path, file.sha256]));
  const messages: string[] = [];
  let changed = false;
  for (const file of files) {
    const fullPath = resolveFrom(root, file.path);
    if (!existsSync(fullPath)) {
      mkdirSync(dirname(fullPath), { recursive: true });
      writeFileSync(fullPath, file.content, "utf8");
      messages.push(`created ${file.path}`);
      changed = true;
      continue;
    }
    if (!update) {
      messages.push(`skipped existing ${file.path}`);
      continue;
    }
    const current = readFileSync(fullPath, "utf8");
    if (previous.get(file.path) !== undefined && previous.get(file.path) === sha256(current)) {
      writeFileSync(fullPath, file.content, "utf8");
      messages.push(`updated ${file.path}`);
      changed = true;
    } else {
      messages.push(`skipped divergent ${file.path}`);
    }
  }
  if (changed || manifest?.agent === agent) writeAgentManifest(root, agent, files);
  return messages;
}

function normalizeProfile(value: string | undefined): Profile | undefined {
  if (value === undefined) return "Standard";
  const lowered = value.toLowerCase();
  if (lowered === "lean") return "Lean";
  if (lowered === "standard") return "Standard";
  if (lowered === "strict") return "Strict";
  return undefined;
}

function normalizeAgent(value: string | undefined): Agent | undefined {
  if (value === undefined) return "codex";
  const lowered = value.toLowerCase();
  return ["codex", "claude", "cursor", "copilot"].includes(lowered) ? lowered as Agent : undefined;
}

function normalizeLanguage(value: string | undefined): Language | undefined {
  if (value === undefined) return "ja";
  const lowered = value.toLowerCase();
  if (lowered === "ja" || lowered === "ja-jp") return "ja";
  if (lowered === "en" || lowered === "en-us") return "en";
  return undefined;
}

export function runInit(root: string, options: InitOptions = {}): number {
  const profile = normalizeProfile(options.profile);
  if (!profile) {
    console.error("Profile must be lean, standard, or strict");
    return 2;
  }
  const agent = normalizeAgent(options.agent);
  if (!agent) {
    console.error("Agent must be codex, claude, cursor, or copilot");
    return 2;
  }
  const lang = normalizeLanguage(options.lang);
  if (!lang) {
    console.error("Language must be ja or en");
    return 2;
  }

  for (const dir of profileRequiredDirs(profile)) {
    mkdirSync(resolveFrom(root, dir), { recursive: true });
  }

  const wbs: WbsDocument = {
    schemaVersion: "0.1.0",
    id: "scwbs-project",
    name: "SC-WBS Project",
    rootId: "node-project",
    nodes: [
      {
        id: "node-project",
        parentId: null,
        code: "1",
        name: "Project",
        type: "deliverable",
        status: "planned",
        progressPercent: 0,
        extensions: {
          scwbs: {
            status: "Not Started"
          }
        }
      }
    ],
    relations: [],
    resources: [
      {
        id: "resource-human",
        name: "Human",
        type: "role"
      },
      {
        id: "resource-ai",
        name: "AI Agent",
        type: "role"
      }
    ],
    artifacts: [],
    metadata: {
      createdBy: "scwbs",
      language: lang === "ja" ? "ja-JP" : "en-US"
    },
    extensions: {
      scwbs: {
        profile,
        agent,
        lang
      }
    }
  };

  const created: string[] = [];
  if (writeIfMissing(root, defaultWbsPath, `${JSON.stringify(wbs, null, 2)}\n`)) created.push(defaultWbsPath);
  if (writeIfMissing(root, defaultRegistryPath, stringifySimpleYaml({ projectId: "scwbs-project", contracts: [] }))) created.push(defaultRegistryPath);
  created.push(...syncAgentFiles(root, agent, lang, false));

  if (created.length === 0) {
    console.log("scwbs init: nothing to create");
  } else {
    for (const item of created) console.log(`created ${item}`);
  }
  return 0;
}

export function runAgentUpdate(root: string, options: AgentUpdateOptions = {}): number {
  const wbsPath = resolveFrom(root, defaultWbsPath);
  let configuredAgent: string | undefined = options.agent;
  let language: Language = "ja";
  if (existsSync(wbsPath)) {
    try {
      const wbs = JSON.parse(readFileSync(wbsPath, "utf8")) as WbsDocument;
      const settings = wbs.extensions?.scwbs as { agent?: string; lang?: string } | undefined;
      configuredAgent ??= settings?.agent;
      if (settings?.lang === "en") language = "en";
    } catch {
      // The normal check command reports malformed WBS content; update remains fail-closed here.
    }
  }
  const agent = normalizeAgent(configuredAgent);
  if (!agent) {
    console.error("Agent must be codex, claude, cursor, or copilot");
    return 2;
  }
  for (const message of syncAgentFiles(root, agent, language, true)) console.log(message);
  return 0;
}
